# densenet // L=190, k=40, num_classes=100
'044b8c6cb6955787de239cc58180bc693c01a97c3c29dd8ec5b6c222':
    dir_name: densenet_large_numclasses_100
    file_name: model_best.pth.tar
    link: https://drive.google.com/u/0/uc?export=download&confirm=ilUf&id=1Mwr6pmdWN7r4wgmE1nYqEUDyuwLt5ce5
# simplenet // num_classes=100
'25b245b7bf273bea50974f22893e3329d285d9cbf5c99ba3942af8c1':
    dir_name: simplenet_numclasses_100
    file_name: model_best.pth.tar
    link: https://drive.google.com/u/0/uc?id=12rKUVZNDucVfxi4G3fLJwahF2dxKDOfZ&export=download
